### ISSUE TITLE
GCC 4.9

### ISSUE THREAD

**Issue by h-2** [phusion/holy-build-box#2]
Wow, this project is really something we have been looking for and much simpler than our current collection of outdated centos virtualbox images. It even has up to date cmake :+1: 

But, we do require at least GCC 4.9, because GCC 4.8 is broken for really many C++11 features. Do you have any plans on updating? I actually think quite a few projects require GCC>=4.9 now...

Thank you very much!

**Comment by FooBarWidget** [comment]
Unfortunately this is not possible. We depend on RPMs for GCC. There are no GCC 4.9 RPMs for CentOS 5.

**Comment by truatpasteurdotfr** [comment]
gcc-4.9 from devtoolset-3 (for CentOS-6 and CentOS-7) is not available for CentOS-5, and CentOS-5 is going EOL very soon https://wiki.centos.org/About/Product and upstream https://access.redhat.com/support/policy/updates/errata.

**Comment by FooBarWidget** [comment]
I understand. But I'm using CentOS 5 for the purpose of being able to compile against an old glibc. I guess that we are fast approaching the point where I can abandon CentOS 5 and at least switch to CentOS 6, but we aren't there yet.

**Comment by h-2** [comment]
> and at least switch to CentOS 6, but we aren't there yet.

If the plan is to switch to a c6-based hbb anyways, could you maybe already offer it in parallel to the c5-based one? I don't want to sound demanding and I don't know how much work it would be, but if it is the plan for the future anyway? [we unfortunately can't use the current one at all]

Thank you!

**Comment by FooBarWidget** [comment]
I could look into it in the near future, but since I am generally very busy
with my day job at Phusion I cannot make any guarantees as to when that
will happen. If I need it for something commercially Phusion related (which
isn't the case yet) then it will happen faster, but if not then it depends
on my free time and mood. If you need it within some sort of guaranteed
time frame then the best way to achieve that is to do it yourself.

Sent from my Android phone.

Op 27 sep. 2016 8:48 p.m. schreef "Hannes Hauswedell" <
notifications@github.com>:

**Comment by kdmurray91** [comment]
Sorry to reopen this issue, but I've patched the build script and dockerfiles to use centos 6 base images, and use gcc 5.2.1 from software collections. I needed this to build static binaries of software using SeqAn (@h-2 et al.'s package). This is in the [kdm-centos6](https://github.com/phusion/holy-build-box/compare/master...kdmurray91:kdm-centos6) branch of mine.

 @FooBarWidget Would you welcome this as a PR? Otherwise this work will be kept as a (probably unmaintained) fork. More than happy to make changes to ease merging of course.

**Comment by FooBarWidget** [comment]
Thanks for the pull request.

Looking at how much other work I have to do, I think it is unwise to maintain two versions of Holy Build Box. I would definitely be interested in your PR, but I'd rather switch to CentOS 6 altogether rather than providing two versions in parallel.

I've re-evaluated the situation. CentOS 6 uses glibc 2.12. According to [Wikipedia](https://en.wikipedia.org/wiki/GNU_C_Library#Version_history) this means compatibility for Debian >= 7 and Ubuntu >= 12.04. Furthermore, CentOS 5 will be EOL'ed in March 2017. RHEL 5 will be fully EOL'ed in 2020 but I think it's too ridiculous to wait that long. So I suppose CentOS 6 is fine nowadays.

I'll reopen this ticket as a reminder and do something about it at my next opportunity.

As for your PR, I've got a couple of comments:

 - We use tabs, not spaces, for indenting. Your activate_func.sh has mixed tabs and spaces.
 - You use the python27 SCL, but Holy Build Box already installs Python by itself. You should either not use the python27 SCL, or you should make Holy Build Box not install Python by itself.
 - Have you double checked all documentation against your image? All documentation must be compatible with your changes.

**Comment by FooBarWidget** [comment]
We now have gcc 8.3.
