### ISSUE TITLE
arm64 version?

### ISSUE THREAD

**Issue by alex9434** [phusion/holy-build-box#42]
Hello, are there any plans to add an arm64 version  of the tool?

**Comment by nightlark** [comment]
Not at the moment (as far as I know). It looks like there is an arm64 centos:7 docker image, so if everything compiles on arm64 it could be fairly straightforward to add one.

Checking these, it looks like building an arm64 docker image on x86 is easy enough, but I don't have things setup to test an arm64 image at the moment:
https://www.docker.com/blog/multi-arch-images/
https://www.stereolabs.com/docs/docker/building-arm-container-on-x86/

I think knowing if it works on arm64 would be interesting -- if you are able to build and test an arm64 Docker image for hbb, knowing if it just works or if there are other bugs that need fixing would be helpful towards adding support. Otherwise, I might get an arm64 system Q3/4 this year, at which point I could play with it some.

**Comment by cyagon** [comment]
Im was able to build an ARM image:
https://hub.docker.com/repository/docker/cyagon/holy-build-box

Maybe its possible to build an ppc64le image as well.

**Comment by cyagon** [comment]
Seems like ppc64le failed. But i was able to build https://github.com/masonr/yet-another-bench-script/tree/master/bin in ARM64, so it should be good. Anyway, here is how i built ARM64:

- Deployed Hetzners CCX22
- Ubuntu 20.04 with "linux-virtual-hwe-20.04" Kernel (because why not?)
- Installed Docker and enabled experimental features
- Executed `docker run --privileged --rm tonistiigi/binfmt --install all` to install qemu-user-static. `https://github.com/multiarch/qemu-user-static` has some problems, as explained here: https://github.com/envoyproxy/envoy/pull/15386
- Made a docker buildx-worker with "docker buildx create --use"
- Logged into Docker/Github Container Registry, opened a tmux session and executed this:
`docker buildx build --rm --pull --push --platform=linux/arm64,linux/amd64 -t ghcr.io/YOURNAMEHERE/holy-build-box/hbb:3.0.2 -t ghcr.io/YOURNAMEHERE/holy-build-box/hbb:latest -f Dockerfile-64 .
`
